### ISSUE TITLE
No version in hackage with a constraint for base-4.11.1.0 (ghc 8.4.4)

### ISSUE THREAD

**Issue by code5hot** [nomeata/ghc-heap-view#25]
No version in hackage with a constraint for base-4.11.1.0 (ghc 8.4.4).

0.5.10 requires  base < 4.11 and 0.6.0 requires base >= 4.12, 4.11.1 is totally excluded.

ghc-8.4.4 comes with the latest version of ubuntu.

**Comment by nomeata** [comment]
Can you check if `0.5.10` works with `ghc-8.4.4`? If so I can simply extend the bound on hackage.

**Comment by code5hot** [comment]
I checked out 4f5fff4b3 and it built but I also cant install ghc-vis yet to
fully test due to the usual cabal incompatibility issues.

Test.hs fails under runhaskell with Test.hs: user error (Expected
ConsClosure).

**Comment by code5hot** [comment]
I note that the shakespeare I tried calls itself 0.5.11

I dont know how to try 0.5.10 with 8.4.4 because cabal wont install it. Can
you tell me how to try it?

**Comment by code5hot** [comment]
Shakespeare? My phone's auto complete is getting worse... SHA

**Comment by nomeata** [comment]
> I checked out [4f5fff4](https://github.com/nomeata/ghc-heap-view/commit/4f5fff4b3fbc41e2555612fe95b692f6821b43ab) and it built but I also cant install ghc-vis yet to fully test due to the usual cabal incompatibility issues. Test.hs fails under runhaskell with Test.hs: user error (Expected ConsClosure).

Did you try `cabal test`?

**Comment by code5hot** [comment]
That passed

**Comment by nomeata** [comment]
Uploaded 0.5.11, thanks
