### ISSUE TITLE
Unexpected thunks from AssertNF family functions

### ISSUE THREAD

**Issue by jberryman** [nomeata/ghc-heap-view#28]
I'm struggling to understand the output I'm getting from `assertNF` family of functions. For instance, in my code I have:

    do
    let !pState = P threadRef metrics
    $assertNFHere pState

And I get the output:

    parameter at src-lib/Foo/State.hs:101:5 not in normal form: 1 thunks found: 
    _thunk (P (Thread ... ... ...) (R ... ... ... ...))

I don't know what to make of that. `P` and `R` all have strict fields.

**Comment by jberryman** [comment]
oh, I guess `_thunk x y` means a thunk application to arguments `x` and `y`?

So maybe a thunk is actually being introduced in the body of the expanded `assertNFHere` splice?

Does `...` mean "the rest of this stuff is fully evaluated"?

What about this one?:

    parameter at src-lib/Floot/Server.hs:146:3 not in normal form: 1 thunks found: 
    _thunk (_thunk _thunk())

This looks like more than one thunk to me. And what does `_thunk()` signifiy?

**Comment by jberryman** [comment]
And what is displayed in the case that there is a thunk somewhere deep in a structure? Is the outer structure displayed in the log or do we lose that context? I don't see an example in my log

**Comment by nomeata** [comment]
I think it tried to display the expression “deep enough” to show the thunks; further subexpressions are elided using `...`.

But yes, it  seems to be a bug that there is an outermost thunk. Is the expression `P threadRef metrics` maybe _static_? If so, can you try to include some local variable (function parameter) in it, to avoid it beging static?

**Comment by jberryman** [comment]
Hm, no it's not static, a little more context we have:

```
do
metrics <- initMetrics
threadRef <- forkIO ...
let !pState = P threadRef metrics
$assertNFHere pState
```

**Comment by nomeata** [comment]
Hmm, maybe look at `-ddump-splices` and see if the splice introduces visible unwanted laziness?

**Comment by jberryman** [comment]
Ah it seems compiling with code coverage was causing all the unexpected thunks
