### ISSUE TITLE
Pretty printing of nullary constructors shows an extra argument

### ISSUE THREAD

**Issue by Lysxia** [nomeata/ghc-heap-view#32]
```
main = do
  t <- buildHeapTree 33 ()
  putStrLn (ppHeapTree t)

-- Actual output:     () 5047672
-- Expected output:   ()
```

(Tested with GHC 8.10)

Nullary constructors are represented with a non-pointer field. Is there any way to distinguish them from unary constructors such as `I# :: Int# -> Int`?

**Comment by nomeata** [comment]
Does this also apply to the `ghc-heap` library shipped with GHC (since 8.6 or so)? If so, maybe report at https://gitlab.haskell.org/ghc/ghc/-/issues/.

(I still need to properly deprecated this library now that GHC officially supports this.)

**Comment by Lysxia** [comment]
> I still need to properly deprecated this library now that GHC officially supports this.

I can't find `buildHeapTree` and `ppHeapTree` in ghc-heap though. Is the plan that even pretty-printing support should be in ghc-heap?

That said the core issue might be in ghc-heap itself, I'll ask over there.

**Comment by nomeata** [comment]
> I can't find buildHeapTree and ppHeapTree in ghc-heap though. Is the plan that even pretty-printing support should be in ghc-heap?

Ah, right, I guess `ghc-heap-view` is building higher-level things on top of it these days. One should think I should know these things… oh well.

> That said the core issue might be in ghc-heap itself, I'll ask over there.

Yes, possible.

**Comment by Lysxia** [comment]
As it turns out, that is indeed a problem with the representation of nullary constructors itself, which are tagged the same as constructors with one unboxed field. So this is mainly an issue in GHC. Feel free to close this.

**Comment by nomeata** [comment]
Vaguely matches my recollection. Thanks for investigating!
