### ISSUE TITLE
Surprising behaviour viewing unboxed fields

### ISSUE THREAD

**Issue by expipiplus1** [nomeata/ghc-heap-view#39]
Take for example this data type

```haskell
data Foo = Foo {-# UNPACK #-} !Int (Maybe Int)
x = Foo 5 (Just 10)
```

Loading this up in GHCi and running `printHeap` yields the following output:

```haskell
λ> :printHeap x
Foo (I# 5) (Just (I# 10))
```

The first `I#` is a little surprising, as I would have expected that field to be unboxed in the `Foo` constructor. I would have expected output something more like

```haskell
Foo 5# (Just (I# 10))
```

Or even better (making indirections explicit, I suppose this is straying a little from what `ppHeapGraph` was intended to do though):

```haskell
let i1 = I# 10
    i2 = Just i1
in Foo 5# i2
```

**Comment by nomeata** [comment]
Could it be that the unpacking doesn't happen with GHCi? Try loading it from a compiled file!

**Comment by expipiplus1** [comment]
Ah, This seems to work more as expected, thanks!

```
λ> :printHeap x
Foo (Just (I# 11)) 5
```

From a glance at `ppHeapGraph` it seems that it would be quite a simple change to allow being more explicit about indirections (put everything in a `let` binding, rather than just those values with more than one reference). Would adding such an option to `ppHeapGraph` be at all useful do you think?

**Comment by nomeata** [comment]
I'd expect that gets very big quickly then. A constructor is always an indirection, which of course one has to know :-)
