### ISSUE TITLE
Clarify which versions of GHC are supported?

### ISSUE THREAD

**Issue by FranklinChen** [nomeata/ghc-heap-view#6]
Can we clarify which versions of GHC are supported? I see in the Travis build 7.6 through 7.10. I presume 7.4 is not supported then? The reason I ask is I'm trying to determine which GHC versions `ghc-vis` should support https://github.com/def-/ghc-vis/issues/7

**Comment by nomeata** [comment]
The supported versions of GHC can be derived from the dependency on base (which seems to be the best way to tell Cabal what versions of GHC work). Currently, it is `base >= 4.5 && < 4.9` so by https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory that should be GHC-7.4 through 7.10.

But indeed it would be convenient if the package description would clearly state that. Fixed.

**Comment by nomeata** [comment]
(Although I think 7.10 support is only untested so far, and only enabled in the cabal file to get it tested on travis.)

**Comment by FranklinChen** [comment]
OK, I will try to make `ghc-heap-view` build with Travis on GHC 7.4. I am using `ghc-heap-view` OK with 7.10 so far as well as 7.8.

**Comment by nomeata** [comment]
Great to hear that! I’m still on 7.8 (and don’t use it regularly), so I rely on user feedback.

So I conclude that I can release the current git version to hackage?

**Comment by FranklinChen** [comment]
Yeah, sure. I have to confess that I could not get a build on GHC 7.4 and your recent Travis changes didn't put in 7.4. I don't personally care about 7.4 but does anyone else?

**Comment by nomeata** [comment]
Probably not.
